//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2023.05.23 at 11:55:48 PM CEST
//

package tk.xenon98.laundryapp.driver.xml;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;
import java.math.BigInteger;
import java.util.Objects;

/**
 * <p>
 * Java class for hierarchyType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="hierarchyType"&gt;
 * &lt;complexContent&gt;
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 * &lt;sequence&gt;
 * &lt;element name="node" type="{}nodeType"/&gt;
 * &lt;/sequence&gt;
 * &lt;attribute name="rotation" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 * &lt;/restriction&gt;
 * &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "hierarchy", propOrder = {"node"})
public class Hierarchy {

    @XmlElement(required = true)
    protected Node node;
    @XmlAttribute(name = "rotation")
    protected long rotation;

    /**
     * Gets the value of the node property.
     *
     * @return possible object is {@link Node }
     *
     */
    public Node getNode() {
        return node;
    }

    /**
     * Sets the value of the node property.
     *
     * @param value
     *            allowed object is {@link Node }
     *
     */
    public void setNode(Node value) {
        this.node = value;
    }

    /**
     * Gets the value of the rotation property.
     *
     * @return possible object is {@link BigInteger }
     *
     */
    public long getRotation() {
        return rotation;
    }

    /**
     * Sets the value of the rotation property.
     *
     * @param value
     *            allowed object is {@link BigInteger }
     *
     */
    public void setRotation(long value) {
        this.rotation = value;
    }

    @Override
    public boolean equals(final Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        final Hierarchy hierarchy = (Hierarchy) o;
        return rotation == hierarchy.rotation && Objects.equals(node, hierarchy.node);
    }

    @Override
    public int hashCode() {
        return Objects.hash(node, rotation);
    }

    @Override
    public String toString() {
        return "Hierarchy{" + "node=" + node + ", rotation=" + rotation + '}';
    }
}
